force-app/main/default/objects/Product2/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <label>MSRP</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <label>Picture_URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductController.cls
public with sharing class ProductController {
    
    @AuraEnabled(cacheable=true)
    public static Object getProducts(string searchKey){
        
        string whereClause = '';
        string key = '';

        try {
            if(searchKey != null){
                if(!string.isEmpty(searchKey)){
                    key = '%' + searchKey + '%';
                    whereClause = 'WHERE Name LIKE :key';
                }

            }

            Object[] products = Database.query(
                'SELECT Id, Name, MSRP__c, Picture_URL__c FROM Product2 ' + 
                whereClause +
                '  WITH SECURITY_ENFORCED ' +
                ' ORDER BY Name'
            );
            return products;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}