force-app/main/default/objects/Word_Shuffle__c/Word_Shuffle__c.object-meta.xml
<CustomObject>
    <label>Word Shuffle</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Word Shuffles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Word_Shuffle__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Word_Shuffle__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GameResultController.cls
public with sharing class GameResultController {
  
    @AuraEnabled
    public static List<Word_Shuffle__c> getResults(){
        try {
             string userId = UserInfo.getUserId();
            List<Word_Shuffle__c> results = [
                SELECT Id, Name, Result__c, Mode__c , CreatedDate
                FROM Word_Shuffle__c
                WHERE CreatedById =:userId AND CreatedDate = LAST_N_DAYS:1
                ORDER BY CreatedDate DESC
            ] ;

            return results;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}