force-app/main/default/objects/Word_Shuffle__c/Word_Shuffle__c.object-meta.xml
<CustomObject>
    <label>Word Shuffle</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Word Shuffles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Word_Shuffle__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Word_Shuffle__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BoardPanelController.cls
public with sharing class BoardPanelController {
    
    @AuraEnabled
    public static string addResult(string result , string mode){
        try {
            Word_Shuffle__c gameResult = new Word_Shuffle__c(Result__c = result, Mode__c = mode);
            insert gameResult;
            return 'Success';

            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }
}